// import Chuttamalle from "./audios"
import Chuttamalle from "./audios/Chuttamalle.mp3";
import ayudhapooja from "./audios/Ayudhapooja.mp3";
import fear from "./audios/Fear.mp3";
import thandavam from "./audios/Devara-Thandavam.mp3";
import Daavudi from "./audios/Daavudi.mp3";
import godarigattu from "./audios/Godarigattu.mp3"
import meenu from "./audios/Meenu.mp3"
import pushpa from "./audios/Pushpapushpa.mp3"
import kissik from "./audios/Kissik.mp3"
import sooseki from "./audios/Sooseki.mp3";
import peelings from "./audios/Peelings.mp3";
import shekhawat from './audios/Dammuntepattukora.mp3'
import anuvanuvu from './audios/Anuvanuvu.mp3'
import srimathigaru from "./audios/srimathigaru.mp3"
import nijamakala from "./audios/Nijamaakalaa.mp3"
import fire from "./audios/firesong.mp3"
import mannimpu from './audios/Mannimpu.mp3'
import minnale from "./audios/Heyminnale.mp3"
export const Telugu = [
  {
    id: 0,
    title: "Godari Gattu",
    singer: "Ramana Gogula and Madhupriya",
    movie: "Sankrantiki Vasthunnam",
    language: "Telugu",
    year: 2024,
    audio: godarigattu,
    image: "https://i.scdn.co/image/ab67616d0000b273b3b86e8e5542f7b736a2cdfb",
    description: "A soulful melody with heartfelt lyrics.",
    duration: "3:50",
  },
  {
    id: 1,
    title: "Meenu Song",
    artist: "Bheems Ceciroleo",
    movie: "Sankrantiki Vasthunnam",
    language: "Telugu",
    year: 2024,
    audio: meenu,
    image:"https://i.scdn.co/image/ab67616d00001e0287d1153ce3b5c92dfe748d5f",
    description: "A soothing track with deep emotions.",
    duration: "4:00",
  },
  {
    id: 2,
    title: "Chuttamalle",
    artist: "Anirudh Ravichander, Shilpa Rao, Ramajogayya Sastry",
    movie: "Devara Part-1",
    language: "Telugu",
    year: 2024,
    audio: Chuttamalle,
    image: "https://i.scdn.co/image/ab67616d0000b2736d97b3dc154dfdbe2321fb5c",
    description: "A calming song with a mix of old and new music styles.",
    duration: "3:45",
  },
  {
    id: 3,
    title: "Ayudha Pooja",
    artist: "Kaala Bhairava",
    movie: "Devara Part-1",
    language: "Telugu",
    year: 2024,
    audio: ayudhapooja,
    image:
      "https://image-cdn-ak.spotifycdn.com/image/ab67706c0000da841761f97506b0cd40c5c6d457",
    description: "A powerful song with strong beats and inspiring vocals.",
    duration: "4:10",
  },
  {
    id: 4,
    title: "Fear Song",
    artist: "Anirudh Ravichander and Ramajogayya Sastry",
    movie: "Devara Part-1",
    language: "Telugu",
    year: 2024,
    audio: fear,
    image: "https://i.scdn.co/image/ab67616d0000b2738591a24a47e09545b988f9b2",
    description: "A song with a mysterious vibe and intense music.",
    duration: "3:55",
  },
  {
    id: 5,
    title: "Thandavam",
    artist: "Anirudh Ravichander",
    movie: "Devara Part-1",
    language: "Telugu",
    year: 2024,
    audio: thandavam,
    image: "https://i.scdn.co/image/ab67616d0000b2735280788ee7502153c9377477",
    description: "A powerful song with strong beats and moving vocals.",
    duration: "4:00",
  },
  {
    id: 6,
    title: "Daavudi",
    artist: "Nakash Aziz, Akasa and Anirudh Ravichander",
    movie: "Devara Part-1",
    language: "Telugu",
    year: 2024,
    audio: Daavudi,
    image: "https://i.scdn.co/image/ab67616d0000b273c55f82e66732fdf3f600dce7",
    description: "A soft song full of love and emotion.",
    duration: "4:20",
  },
  {
    id: 7,
    title: "Pushpa Raj Anthem",
    artist: "Vijay PrakashNakash Aziz, Deepak Blue, Mika Singh, Vijay Prakash, Ranjith Govind, and Timir Biswas",
    movie: "Pushpa 2: The Rule",
    language: "Telugu",
    year: 2024,
    audio: pushpa,
    image: "https://i.scdn.co/image/ab67616d00001e028cbf4925111458bccb1cd13d",
    description: "A song celebrating Pushpa Raj with energetic beats.",
    duration: "3:35",
  },
  {
    id: 8,
    title: "Kiss kissik",
    artist: "Devi Sri Prasad, Sublahshini",
    movie: "Pushpa 2: The Rule",
    language: "Telugu",
    year: 2024,
    audio: kissik,
    image: "https://i.scdn.co/image/ab67616d0000b273f9e02b6c00650fd4f43c1db5",
    description: "A powerful and intense track with strong beats",
    duration: "3:25",
  },
  {
    id: 9,
    title: "Sooseki",
    artist: "Devi Sri Prasad",
    movie: "Pushpa 2: The Rule",
    language: "Telugu",
    year: 2024,
    audio: sooseki,
    image: "https://i.scdn.co/image/ab67616d00001e02bde2708d57b1fbb64ca2a233",
    description: "A vibrant track with energetic beats.",
    duration: "3:40",
  },
  {
    id: 10,
    title: "Peelings Song",
    artist: "Shankarr Babu Kandukoori, Laxmi Dasa, Devi Sri Prasad",
    movie: "Pushpa 2: The Rule",
    language: "Telugu",
    year: 2024,
    audio: peelings,
    image: "https://i.scdn.co/image/ab67616d00001e029c3b8606a83a49694b48a126",
    description: "A quirky and upbeat track full of energy.",
    duration: "3:45",
  },
  {
    id: 11,
    title: "Dammuntey Pattukora",
    artist: "Allu Arjun,Devi Sri Prasad",
    movie: "Pushpa 2: The Rule",
    language: "Telugu",
    year: 2024,
    audio: shekhawat,
    image: "https://i.scdn.co/image/ab67616d00001e02a99409c57c0ba55fdb2ae9ca",
    description: "A playful track with fun rhythms.",
    duration: "4:00",
  },

  {
    id: 12,
    title: "Anuvanuvu",
    artist: "Arijit Singh",
    movie: "om bheem bush",
    language: "Telugu",
    year: 2024,
    audio: anuvanuvu,
    image: "https://c.saavncdn.com/000/Om-Bheem-Bush-Telugu-2024-20240401231417-500x500.jpg",
    description: "A heartfelt song with deep emotions and soothing music.",
    duration: "4:05",
  },
  {
    id: 13,
    title: "Srimathigaru",
    artist: "G. V. Prakash Kumar, Shweta Mohan, and Vishal Mishra",
    movie: "Lucky Bhaskar",
    language: "Telugu",
    year: 2024,
    audio: srimathigaru,
    image: "https://i.scdn.co/image/ab67616d0000b273e719267835e27042f386738a",
    description: "A sweet and romantic love song filled with charm.",
    duration: "3:50",
  },
  {
    id: 14,
    title: "Nijamakala",
    artist: "Armaan Malik",
    movie: "Lucky Bhaskar",
    language: "Telugu",
    year: 2024,
    audio: nijamakala,
    image: "https://i.scdn.co/image/ab67616d0000b273e6c98d0eba7163edc802bd27",
    description: "A heartfelt track about truth and emotions",
    duration: "3:40",
  },
  
  {
    id: 15,
    title: "Fire",
    artist: "Arijit Singh",
    movie: "Kanguva",
    language: "Tamil",
    year: 2024,
    audio: fire,
    image: "https://i.scdn.co/image/ab67616d0000b273881d3f0bafa13d854ec3b051",
    description: "An energetic and powerful anthem that ignites passion",
    duration: "3:45"
  },
  {
    id: 16,
    title: "Mannimpu",
    artist: "Sid Sriram",
    movie: "Kanguva",
    language: "Tamil",
    year: 2024,
    audio: mannimpu,
    image: "https://i.scdn.co/image/ab67616d0000b2732005f3053bf6df284f413252",
    description: "A hauntingly beautiful track with deep emotions.",
    duration: "5:10"
  },
  {
    id: 17,
    title: "Minnale",
    artist: "Haricharan",
    movie: "Amaran",
    language: "Tamil",
    year: 2024,
    audio: minnale,
    image: "https://i.scdn.co/image/ab67616d0000b273eea0c06f10fd411eaa6f9230",
    description: "A soothing melody that touches the heart.",
    duration: "4:30"
  }
  
];
